config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, except:[ :index, :show ]
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :body, presence: true
    
    belongs_to :post
    belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord

    validates :title, :body, presence: true
    
    belongs_to :user
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [ :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:new, :create, :update, :delete]

  # GET /comments/new
  def new
    @comment = current_user.comments.build
    p "HEY HERE IS MY COMMENT"
    p params
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
        redirect_to root_path
    else
        flash[:alert] = @comment.errors.full_messages[0]
        render 'posts/show'
    end

      ##@post = Post.find(params[:id])
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(comment_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:new, :create, :update, :delete]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
     @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)
    @posts = Post.all

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :index }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:first_name,:last_name, :username, :email, :password, :password_confirmation)
	end

	def acount_update_params
		params.require(:user).permit(:first_name,:last_name, :username, :email, :password, :password_confirmation, :current_password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
    <%= form_with(model: [ @post, @post.comments.new  ], local: true) do |form| %>
      <div class="field">
        <%= form.text_area :body, class:"form-control"%>
      </div>
      <div class="actions col-12 d-flex justify-content-end p-0">
        <%= form.submit "Post Comment" , class:"btn btn-primary mt-3" %>
      </div>
    <% end %>

app/views/comments/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark justify-content-between">
        <%= link_to "Members-Only", root_path , {class:"navbar-brand"} %>

        <div class="d-flex ">
            <% if user_signed_in? %>
                <% p current_user %>

                <div class="text-light vertical-center mr-2 mt-2">
                    <span>Welcome </span>
                    <%= current_user.username || "No Username Available" %>
                </div>
                <%= link_to "Logout", destroy_user_session_path, method: :delete,
                class:"btn btn-outline-danger my-2 my-sm-0" %>
            <% else %>
                <%= link_to 'Sign In', new_user_session_path, class: "btn btn-outline-info mr-2 my-2 my-sm-0" %>
                <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-outline-success my-2 my-sm-0" %>
            <% end %>
        </div>
    </nav>

    <% if notice %>
        <div class="alert alert-primary" role="alert">
          <%= notice %>
        </div>
    <% end %>

    <% if alert %>
        <div class="alert alert-danger" role="alert">
          <%= alert %>
        </div>
    <% end %>
    <div class="container p-3">
        <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="col-6 mx-auto border border-dark p-3 mt-3">
    <%= form_with(model: @post, local: true) do |form| %>
      <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field mb-2">
        <%= form.label :title %>
        <%= form.text_field :title, class:"form-control"%>
      </div>

      <div class="field">
        <%= form.label :body %>
        <%= form.text_area :body, class:"form-control"%>
      </div>
      <div class="actions col-12 d-flex justify-content-end p-0">
        <%= form.submit class:"btn btn-primary mt-3 " %>
      </div>
    <% end %>
</div>

app/views/posts/edit.html.erb
<div class="text-center">
    <h1>Editing Post</h1>
</div>

<%= render 'form', post: @post %>

<div class="col-6 d-flex justify-content-end p-0 mx-auto">
    <%= link_to 'Show', @post, class:"mr-2" %>
    <%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<% if user_signed_in? %>
     <%= render 'form' %>
<% end %>

<% @posts.each do |post| %>
  <div class="col-6 mx-auto border border-dark rounded mt-3 p-3">
      <h4><%= post.title %></h4>

      <% if user_signed_in? %>
        <p>Written by: <%= post.user.username %></p>
      <% else %>
        <p>Written by: anonymous</p>
      <% end %>

      <p>Posted <%= distance_of_time_in_words(Time.now, post.created_at) %> ago </p>

      <p><%= post.body %></p>

      <div class="d-flex">
        <%= link_to 'Show', post, class: "mr-2" %>
        <% if post.user.username == (current_user && current_user.username) %>
            <%= link_to 'Edit', edit_post_path(post), class:"mr-2" %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } ,class:"mr-2" %>
        <% end %>
      </div>

      <br/>

      <h5><ul class="p-0">Comments</ul></h5>
      <% if post.comments.length() > 0 %>
          <% post.comments.each do |comment| %>
             <div class="ml-3 mb-3">
                <p><%= comment.body %></p>
                <% if user_signed_in? %>
                    <div>Commented By: <%= comment.user.username %></div>
                <% else %>
                    <div>Commented By: anonymous</div>
                <% end %>
             </div>
          <% end %>
      <% end %>

      <%= link_to 'Comment', post_path(post), class:"btn btn-primary" %>

  </div>
<% end %>

app/views/posts/show.html.erb
<div class="col-6 mx-auto p-3 border border-dark">
    <p>
      <h4><%= @post.title %></h4>
    </p>

    <p>Written By:
        <span>
            <% if user_signed_in? %>
                <%= @post.user.username %>
            <% else %>
                'anonymous'
            <% end %>
        </span>
    </p>

    <p>
      <%= @post.body %>
    </p>

    <h5>Comments</h5>

    <% if @post.comments.length() > 0 %>
        <% @post.comments.each do |comment| %>
            <% if comment.body.length() > 0 %>
            <div class="ml-3 mb-3">
               <p><%= comment.body %></p>
               <% if user_signed_in? %>
                   <div>Commented By: <%= comment.user.username %></div>
               <% else %>
                   <div>Commented By: anonymous</div>
               <% end %>
            </div>
            <% end %>
        <% end %>
    <% end %>

    <div class="mx-auto mt-3">
        <%= render partial: 'comments/form' %>
    </div>

    <div class="d-flex">
        <%= link_to 'Edit', edit_post_path(@post), class:"mr-3" %>
        <%= link_to 'Back', posts_path %>
    </div>

</div>